# Generated by Django 3.2.9 on 2022-04-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile',
            field=models.ImageField(blank=True, default='2.jpg', null=True, upload_to=''),
        ),
    ]
